-- -------------------------------------------------------------
-- 
-- File Name: C:\GIT\pcore_Examples\Receiver_pcore_fifo\MATLAB\codegen\rx_fifo\hdlsrc\fifo_ram.vhd
-- Created: 2013-12-30 11:51:49
-- 
-- Generated by MATLAB 8.3, MATLAB Coder 2.6 and HDL Coder 3.4
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fifo_ram
-- Source Path: rx_fifo_fixpt/fifo_ram
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fifo_ram IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        wr_din                            :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        wr_addr                           :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
        wr_en                             :   IN    std_logic;  -- ufix1
        rd_addr                           :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
        rd_dout                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END fifo_ram;


ARCHITECTURE rtl OF fifo_ram IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_2048x8b
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          wr_addr                         :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
          rd_dout                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_2048x8b
    USE ENTITY work.SimpleDualPortRAM_2048x8b(rtl);

  -- Signals
  SIGNAL rd_dout_tmp                      : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_SimpleDualPortRAM_2048x8b : SimpleDualPortRAM_2048x8b
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => wr_din,  -- ufix8
              wr_addr => wr_addr,  -- ufix11
              wr_en => wr_en,  -- ufix1
              rd_addr => rd_addr,  -- ufix11
              rd_dout => rd_dout_tmp  -- ufix8
              );

  rd_dout <= rd_dout_tmp;

END rtl;

