-- -------------------------------------------------------------
-- 
-- File Name: C:\GIT\Chilipepper_Labs\Labs\Lab_4\MATLAB\codegen\dc_offset_correction\hdlsrc\dc_offset_correction_fixpt.vhd
-- Created: 2014-03-19 12:49:20
-- 
-- Generated by MATLAB 8.3, MATLAB Coder 2.6 and HDL Coder 3.4
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- i_out                         ce_out        1
-- q_out                         ce_out        1
-- rssi_out                      ce_out        1
-- dir_out                       ce_out        1
-- blinky                        ce_out        1
-- d1                            ce_out        1
-- d2                            ce_out        1
-- d3                            ce_out        1
-- d4                            ce_out        1
-- d5                            ce_out        1
-- d6                            ce_out        1
-- d7                            ce_out        1
-- d8                            ce_out        1
-- gain_out                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dc_offset_correction_fixpt
-- Source Path: dc_offset_correction_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dc_offset_correction_fixpt_pkg.ALL;

ENTITY dc_offset_correction_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        i_in                              :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        q_in                              :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        gain_en_in                        :   IN    std_logic;  -- ufix1
        rssi_low_goal_in                  :   IN    std_logic_vector(29 DOWNTO 0);  -- ufix30
        rssi_high_goal_in                 :   IN    std_logic_vector(29 DOWNTO 0);  -- ufix30
        rx_en_in                          :   IN    std_logic;  -- ufix1
        gain_in                           :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        ce_out                            :   OUT   std_logic;
        i_out                             :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12
        q_out                             :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12
        rssi_out                          :   OUT   std_logic_vector(23 DOWNTO 0);  -- ufix24
        dir_out                           :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        blinky                            :   OUT   std_logic;  -- ufix1
        d1                                :   OUT   std_logic_vector(23 DOWNTO 0);  -- ufix24
        d2                                :   OUT   std_logic_vector(23 DOWNTO 0);  -- ufix24
        d3                                :   OUT   std_logic_vector(23 DOWNTO 0);  -- ufix24
        d4                                :   OUT   std_logic_vector(23 DOWNTO 0);  -- ufix24
        d5                                :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        d6                                :   OUT   std_logic_vector(29 DOWNTO 0);  -- ufix30
        d7                                :   OUT   std_logic;  -- ufix1
        d8                                :   OUT   std_logic;  -- ufix1
        gain_out                          :   OUT   std_logic_vector(5 DOWNTO 0)  -- ufix6
        );
END dc_offset_correction_fixpt;


ARCHITECTURE rtl OF dc_offset_correction_fixpt IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL i_in_signed                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL i_in_1                           : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL rx_en_in_1                       : std_logic;  -- ufix1
  SIGNAL tmp                              : std_logic;
  SIGNAL tmp_1                            : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p215tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p215tmp_cast_1                   : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_2                            : std_logic;
  SIGNAL tmp_3                            : std_logic;
  SIGNAL tmp_4                            : std_logic;
  SIGNAL tmp_5                            : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p208tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p208tmp_cast_1                   : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_6                            : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_7                            : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_8                            : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p209tmp_mul_temp                 : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p209tmp_cast                     : signed(37 DOWNTO 0);  -- sfix38_En24
  SIGNAL tmp_9                            : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_10                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_11                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_12                           : std_logic;
  SIGNAL tmp_13                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL p187tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p187tmp_cast_1                   : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL tmp_14                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_15                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_16                           : std_logic;
  SIGNAL tmp_17                           : std_logic;
  SIGNAL tmp_18                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_19                           : std_logic;
  SIGNAL q_in_signed                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL q_in_1                           : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL tmp_20                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p211tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p211tmp_cast_1                   : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_21                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_22                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_23                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_24                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p212tmp_mul_temp                 : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p212tmp_cast                     : signed(37 DOWNTO 0);  -- sfix38_En24
  SIGNAL tmp_25                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_26                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_27                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_28                           : std_logic;
  SIGNAL tmp_29                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p219tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p219tmp_cast_1                   : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_30                           : std_logic;
  SIGNAL tmp_31                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL p185tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p185tmp_cast_1                   : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL tmp_32                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_33                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_34                           : std_logic;
  SIGNAL tmp_35                           : std_logic;
  SIGNAL tmp_36                           : std_logic;
  SIGNAL noise_offset                     : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL tmp_37                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL tmp_38                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL noise_inc                        : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL i_dc                             : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL q_dc                             : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_39                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p205_tmp                         : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p205_tmp_1                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p205_sub_cast                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p205_sub_cast_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p205_sub_temp                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p205_cast                        : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p205_add_temp                    : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p205_cast_1                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p205_sub_cast_2                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p205_sub_cast_3                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p205_sub_temp_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p205_cast_2                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p205_add_temp_1                  : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p205_cast_3                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL tmp_40                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL tmp_41                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_42                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL q_dc_1                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_43                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL p217tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En13
  SIGNAL p217tmp_cast_1                   : signed(24 DOWNTO 0);  -- sfix25_En13
  SIGNAL tmp_44                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p189_tmp                         : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL p189_sub_cast                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p189_sub_cast_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p189_sub_temp                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p189_cast                        : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p189_add_temp                    : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p189_cast_1                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL tmp_45                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p220tmp_mul_temp                 : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p220tmp_cast                     : signed(37 DOWNTO 0);  -- sfix38_En24
  SIGNAL tmp_46                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_47                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL i_dc_1                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_48                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL noise_dec                        : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL tmp_49                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p200_tmp                         : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p200_tmp_1                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p200_sub_cast                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p200_sub_cast_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p200_sub_temp                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p200_cast                        : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p200_add_temp                    : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p200_cast_1                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p200_sub_cast_2                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p200_sub_cast_3                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p200_sub_temp_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p200_cast_2                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p200_add_temp_1                  : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p200_cast_3                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL tmp_50                           : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL alpha_1_cast                     : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL alpha_1_cast_1                   : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL alpha_relop1                     : std_logic;
  SIGNAL tmp_51                           : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_tmp                         : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_tmp_1                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_tmp_2                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_tmp_3                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_tmp_4                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_tmp_5                       : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL p203_sub_cast                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p203_sub_cast_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p203_sub_temp                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p203_cast                        : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p203_add_temp                    : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p203_cast_1                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p203_sub_cast_2                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p203_sub_cast_3                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p203_sub_temp_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p203_cast_2                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p203_add_temp_1                  : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p203_cast_3                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL tmp_52                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_53                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL tmp_54                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p216tmp_mul_temp                 : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL p216tmp_cast                     : signed(37 DOWNTO 0);  -- sfix38_En24
  SIGNAL tmp_55                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_56                           : signed(38 DOWNTO 0);  -- sfix39_En24
  SIGNAL tmp_57                           : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL p213tmp_cast                     : signed(24 DOWNTO 0);  -- sfix25_En13
  SIGNAL p213tmp_cast_1                   : signed(24 DOWNTO 0);  -- sfix25_En13
  SIGNAL p192_tmp                         : signed(23 DOWNTO 0);  -- sfix24_En12
  SIGNAL p192_sub_cast                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p192_sub_cast_1                  : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p192_sub_temp                    : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p192_cast                        : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL p192_add_temp                    : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL p192_cast_1                      : signed(33 DOWNTO 0);  -- sfix34_En12
  SIGNAL i_out_1                          : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL p183i_out_sub_cast               : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p183i_out_sub_cast_1             : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p183i_out_sub_temp               : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL rd_41_reg                        : vector_of_signed12(0 TO 2);  -- sfix12 [3]
  SIGNAL i_out_tmp                        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL q_out_1                          : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL p182q_out_sub_cast               : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p182q_out_sub_cast_1             : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL p182q_out_sub_temp               : signed(24 DOWNTO 0);  -- sfix25_En12
  SIGNAL rd_34_reg                        : vector_of_signed12(0 TO 2);  -- sfix12 [3]
  SIGNAL q_out_tmp                        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL tmp_58                           : std_logic;
  SIGNAL tmp_59                           : std_logic;
  SIGNAL tmp_60                           : std_logic;
  SIGNAL tmp_61                           : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL tmp_62                           : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL tmp_63                           : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL tmp_64                           : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL tmp_65                           : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL tmp_66                           : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL tmp_67                           : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL rssi_inst                        : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL tmp_68                           : std_logic;
  SIGNAL tmp_69                           : std_logic;
  SIGNAL counter                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_70                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_71                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL counter_1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_72                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL p139_tmp                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_73                           : std_logic;
  SIGNAL tmp_74                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_75                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_76                           : std_logic;
  SIGNAL tmp_77                           : std_logic;
  SIGNAL tmp_78                           : std_logic;
  SIGNAL tmp_79                           : std_logic;
  SIGNAL tmp_80                           : std_logic;
  SIGNAL tmp_81                           : std_logic;
  SIGNAL tmp_82                           : std_logic;
  SIGNAL tmp_83                           : std_logic;
  SIGNAL rd_19_reg                        : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL tmp_84                           : std_logic;
  SIGNAL gain_en_in_1                     : std_logic;  -- ufix1
  SIGNAL gain_en_in_2                     : std_logic;  -- ufix1
  SIGNAL tmp_85                           : std_logic;
  SIGNAL tmp_86                           : std_logic;
  SIGNAL tmp_87                           : std_logic;
  SIGNAL tmp_88                           : std_logic;
  SIGNAL tmp_89                           : std_logic;
  SIGNAL tmp_90                           : std_logic;
  SIGNAL tmp_91                           : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_92                           : std_logic;
  SIGNAL tmp_93                           : std_logic;
  SIGNAL tmp_94                           : std_logic;
  SIGNAL tmp_95                           : std_logic;
  SIGNAL tmp_96                           : std_logic;
  SIGNAL tmp_97                           : std_logic;
  SIGNAL tmp_98                           : std_logic;
  SIGNAL tmp_99                           : std_logic;
  SIGNAL tmp_100                          : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL tmp_101                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tmp_102                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tmp_103                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tmp_104                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL rssi_sum                         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tmp_105                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tmp_106                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tmp_107                          : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL tmp_108                          : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL tmp_109                          : signed(47 DOWNTO 0);  -- sfix48_En24
  SIGNAL tmp_110                          : signed(48 DOWNTO 0);  -- sfix49_En24
  SIGNAL tmp_111                          : signed(47 DOWNTO 0);  -- sfix48_En24
  SIGNAL tmp_112                          : signed(48 DOWNTO 0);  -- sfix49_En24
  SIGNAL tmp_113                          : signed(48 DOWNTO 0);  -- sfix49_En24
  SIGNAL rd_55_reg                        : vector_of_signed49(0 TO 1);  -- sfix49 [2]
  SIGNAL tmp_114                          : signed(48 DOWNTO 0);  -- sfix49_En24
  SIGNAL rssi_high_goal_in_unsigned       : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL rd_9_reg                         : vector_of_unsigned30(0 TO 2);  -- ufix30 [3]
  SIGNAL rssi_high_goal_in_1              : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL rssi_low_goal_in_unsigned        : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL rd_10_reg                        : vector_of_unsigned30(0 TO 2);  -- ufix30 [3]
  SIGNAL rssi_low_goal_in_1               : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL tmp_115                          : std_logic;
  SIGNAL tmp_116                          : std_logic;
  SIGNAL tmp_117                          : std_logic;
  SIGNAL tmp_118                          : std_logic;
  SIGNAL tmp_119                          : std_logic;
  SIGNAL tmp_120                          : std_logic;
  SIGNAL tmp_121                          : std_logic;
  SIGNAL tmp_122                          : std_logic;
  SIGNAL rssi_en_out                      : std_logic;  -- ufix1
  SIGNAL rd_13_reg                        : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL rssi_en_out_1                    : std_logic;  -- ufix1
  SIGNAL tmp_123                          : std_logic;  -- ufix1
  SIGNAL p143_tmp                         : std_logic;  -- ufix1
  SIGNAL tmp_124                          : std_logic;
  SIGNAL tmp_125                          : std_logic;  -- ufix1
  SIGNAL timeout                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_126                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_127                          : std_logic;
  SIGNAL tmp_128                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_129                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_130                          : std_logic;
  SIGNAL tmp_131                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_132                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_133                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_134                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_135                          : std_logic;  -- ufix1
  SIGNAL tmp_136                          : std_logic;  -- ufix1
  SIGNAL tmp_137                          : std_logic;  -- ufix1
  SIGNAL tmp_138                          : std_logic;  -- ufix1
  SIGNAL rssi_diff                        : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL alpha_relop1_1                   : std_logic;
  SIGNAL tmp_139                          : std_logic;  -- ufix1
  SIGNAL c                                : signed(49 DOWNTO 0);  -- sfix50_En24
  SIGNAL tmp_140                          : signed(49 DOWNTO 0);  -- sfix50_En24
  SIGNAL p88tmp_cast                      : signed(50 DOWNTO 0);  -- sfix51_En24
  SIGNAL p88tmp_cast_1                    : signed(50 DOWNTO 0);  -- sfix51_En24
  SIGNAL tmp_141                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_142                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL p145_tmp                         : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL p145_cast                        : unsigned(39 DOWNTO 0);  -- ufix40_En8
  SIGNAL p145_cast_1                      : unsigned(39 DOWNTO 0);  -- ufix40_En8
  SIGNAL p145_add_cast                    : unsigned(33 DOWNTO 0);  -- ufix34_En1
  SIGNAL p145_add_temp                    : unsigned(33 DOWNTO 0);  -- ufix34_En1
  SIGNAL p145_cast_2                      : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL tmp_143                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_144                          : std_logic;
  SIGNAL tmp_145                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_146                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL p89c_sub_cast                    : signed(49 DOWNTO 0);  -- sfix50_En24
  SIGNAL p89c_sub_cast_1                  : signed(49 DOWNTO 0);  -- sfix50_En24
  SIGNAL tmp_147                          : std_logic;
  SIGNAL tmp_148                          : signed(49 DOWNTO 0);  -- sfix50_En24
  SIGNAL alpha_relop1_2                   : std_logic;
  SIGNAL tmp_149                          : std_logic;  -- ufix1
  SIGNAL tmp_150                          : std_logic;  -- ufix1
  SIGNAL tmp_151                          : std_logic;
  SIGNAL tmp_152                          : std_logic;  -- ufix1
  SIGNAL tmp_153                          : std_logic;  -- ufix1
  SIGNAL tmp_154                          : std_logic;  -- ufix1
  SIGNAL tmp_155                          : std_logic;  -- ufix1
  SIGNAL tmp_156                          : std_logic;  -- ufix1
  SIGNAL tmp_158                          : std_logic;  -- ufix1
  SIGNAL tmp_159                          : std_logic;  -- ufix1
  SIGNAL tmp_160                          : std_logic;  -- ufix1
  SIGNAL tmp_162                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_163                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_164                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_165                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_166                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_167                          : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL p141_tmp                         : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL tmp_168                          : std_logic;
  SIGNAL tmp_169                          : std_logic;  -- ufix1
  SIGNAL tmp_170                          : std_logic;  -- ufix1
  SIGNAL tmp_171                          : std_logic;
  SIGNAL tmp_172                          : std_logic;
  SIGNAL tmp_173                          : std_logic;
  SIGNAL tmp_174                          : std_logic;
  SIGNAL tmp_175                          : std_logic;
  SIGNAL rssi_out_1                       : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL rd_0_reg                         : vector_of_unsigned24(0 TO 1);  -- ufix24 [2]
  SIGNAL rssi_out_2                       : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_176                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL p147_tmp                         : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL p147_cast                        : unsigned(39 DOWNTO 0);  -- ufix40_En8
  SIGNAL p147_cast_1                      : unsigned(39 DOWNTO 0);  -- ufix40_En8
  SIGNAL p147_add_cast                    : unsigned(33 DOWNTO 0);  -- ufix34_En1
  SIGNAL p147_add_temp                    : unsigned(33 DOWNTO 0);  -- ufix34_En1
  SIGNAL p147_cast_2                      : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL tmp_177                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_178                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_179                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_180                          : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL rssi_latch                       : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL rssi_out_tmp                     : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_181                          : std_logic;
  SIGNAL rd_20_reg                        : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL tmp_182                          : std_logic;
  SIGNAL tmp_183                          : std_logic;  -- ufix1
  SIGNAL tmp_184                          : std_logic;  -- ufix1
  SIGNAL tmp_185                          : std_logic;
  SIGNAL tmp_186                          : std_logic;
  SIGNAL tmp_187                          : std_logic;
  SIGNAL alpha_relop1_3                   : std_logic;
  SIGNAL alpha_relop1_4                   : std_logic;
  SIGNAL dir_en_out                       : std_logic;  -- ufix1
  SIGNAL dir_en_out_1                     : std_logic;  -- ufix1
  SIGNAL rd_3_reg                         : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL dir_en_out_2                     : std_logic;  -- ufix1
  SIGNAL tmp_188                          : std_logic;
  SIGNAL tmp_189                          : std_logic;  -- ufix1
  SIGNAL tmp_190                          : std_logic;  -- ufix1
  SIGNAL tmp_191                          : std_logic;
  SIGNAL tmp_192                          : std_logic;  -- ufix1
  SIGNAL tmp_193                          : std_logic;  -- ufix1
  SIGNAL tmp_194                          : std_logic;  -- ufix1
  SIGNAL tmp_195                          : std_logic;
  SIGNAL tmp_196                          : std_logic;  -- ufix1
  SIGNAL rd_30_reg                        : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL tmp_197                          : std_logic;  -- ufix1
  SIGNAL tmp_199                          : std_logic;  -- ufix1
  SIGNAL tmp_200                          : std_logic;  -- ufix1
  SIGNAL tmp_201                          : std_logic;
  SIGNAL tmp_202                          : std_logic;
  SIGNAL rd_64_reg                        : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL tmp_203                          : std_logic;
  SIGNAL tmp_204                          : std_logic;  -- ufix1
  SIGNAL tmp_205                          : std_logic;  -- ufix1
  SIGNAL tmp_206                          : std_logic;
  SIGNAL tmp_207                          : std_logic;
  SIGNAL tmp_208                          : std_logic;
  SIGNAL alpha_relop1_5                   : std_logic;
  SIGNAL alpha_relop1_6                   : std_logic;
  SIGNAL dir_out_1                        : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL dir_out_2                        : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rd_7_reg                         : vector_of_unsigned2(0 TO 1);  -- ufix2 [2]
  SIGNAL dir_out_3                        : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_209                          : std_logic;
  SIGNAL tmp_210                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_211                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_212                          : std_logic;
  SIGNAL tmp_213                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_214                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_215                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_216                          : std_logic;
  SIGNAL tmp_217                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rd_31_reg                        : vector_of_unsigned2(0 TO 1);  -- ufix2 [2]
  SIGNAL tmp_218                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_220                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_221                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_222                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL dir_latch                        : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL dir_out_tmp                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL tmp_223                          : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL blinky_cnt                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_224                          : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_225                          : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL tmp_226                          : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL tmp_227                          : unsigned(27 DOWNTO 0);  -- ufix28_En37
  SIGNAL blinky_1                         : std_logic;  -- ufix1
  SIGNAL blinky_2                         : std_logic;  -- ufix1
  SIGNAL blinky_3                         : std_logic;  -- ufix1
  SIGNAL blinky_4                         : std_logic;  -- ufix1
  SIGNAL delayMatch_reg                   : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL d1_tmp                           : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d2_1                             : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d2_2                             : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d2_tmp                           : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d3_1                             : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d3_tmp                           : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d4_tmp                           : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL d5_tmp                           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL d6_1                             : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL d6_2                             : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL d6_tmp                           : unsigned(29 DOWNTO 0);  -- ufix30
  SIGNAL d7_1                             : std_logic;  -- ufix1
  SIGNAL d7_2                             : std_logic;  -- ufix1
  SIGNAL d7_3                             : std_logic;  -- ufix1
  SIGNAL d8_1                             : std_logic;  -- ufix1
  SIGNAL d8_2                             : std_logic;  -- ufix1
  SIGNAL rd_18_reg                        : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL gain_in_unsigned                 : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL gain_in_1                        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL gain_in_2                        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL gain_out_1                       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL gain_out_tmp                     : unsigned(5 DOWNTO 0);  -- ufix6

BEGIN
  i_in_signed <= signed(i_in);

  enb <= clk_enable;

  rd_11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      i_in_1 <= to_signed(2#000000000000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        i_in_1 <= i_in_signed;
      END IF;
    END IF;
  END PROCESS rd_11_process;


  rd_14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rx_en_in_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rx_en_in_1 <= rx_en_in;
      END IF;
    END IF;
  END PROCESS rd_14_process;


  
  tmp <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  p215tmp_cast <= resize(i_in_1, 25);
  p215tmp_cast_1 <= p215tmp_cast(23 DOWNTO 0);
  tmp_1 <= resize(p215tmp_cast_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 39);

  
  tmp_2 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_39_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_3 <= tmp_2;
      END IF;
    END IF;
  END PROCESS rd_39_process;


  
  tmp_4 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  p208tmp_cast <= resize(i_in_1, 25);
  p208tmp_cast_1 <= p208tmp_cast(23 DOWNTO 0);
  tmp_5 <= resize(p208tmp_cast_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 39);

  rd_54_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_7 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_7 <= tmp_6;
      END IF;
    END IF;
  END PROCESS rd_54_process;


  p209tmp_mul_temp <= to_signed(2#000111111111111#, 15) * tmp_6;
  p209tmp_cast <= p209tmp_mul_temp(37 DOWNTO 0);
  tmp_8 <= resize(p209tmp_cast, 39);

  rd_46_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_9 <= to_signed(0, 39);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_9 <= tmp_8;
      END IF;
    END IF;
  END PROCESS rd_46_process;


  tmp_10 <= tmp_9 + tmp_5;

  tmp_11 <= tmp_10(35 DOWNTO 12);

  
  tmp_6 <= tmp_11 WHEN tmp_4 = '1' ELSE
      tmp_7;

  
  tmp_12 <= '1' WHEN tmp_6 < 0 ELSE
      '0';

  p187tmp_cast <= resize(tmp_6, 25);
  p187tmp_cast_1 <=  - (p187tmp_cast);
  tmp_13 <= p187tmp_cast_1(23 DOWNTO 0);

  
  tmp_14 <= tmp_6 WHEN tmp_12 = '0' ELSE
      tmp_13;

  rd_52_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_15 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_15 <= tmp_14;
      END IF;
    END IF;
  END PROCESS rd_52_process;


  
  tmp_16 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_33_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_17 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_17 <= tmp_16;
      END IF;
    END IF;
  END PROCESS rd_33_process;


  rd_47_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_18 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_18 <= tmp_11;
      END IF;
    END IF;
  END PROCESS rd_47_process;


  
  tmp_19 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  q_in_signed <= signed(q_in);

  rd_12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      q_in_1 <= to_signed(2#000000000000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        q_in_1 <= q_in_signed;
      END IF;
    END IF;
  END PROCESS rd_12_process;


  p211tmp_cast <= resize(q_in_1, 25);
  p211tmp_cast_1 <= p211tmp_cast(23 DOWNTO 0);
  tmp_20 <= resize(p211tmp_cast_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 39);

  rd_37_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_22 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_22 <= tmp_21;
      END IF;
    END IF;
  END PROCESS rd_37_process;


  
  tmp_21 <= tmp_23 WHEN tmp_19 = '1' ELSE
      tmp_22;

  p212tmp_mul_temp <= to_signed(2#000111111111111#, 15) * tmp_21;
  p212tmp_cast <= p212tmp_mul_temp(37 DOWNTO 0);
  tmp_24 <= resize(p212tmp_cast, 39);

  rd_36_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_25 <= to_signed(0, 39);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_25 <= tmp_24;
      END IF;
    END IF;
  END PROCESS rd_36_process;


  tmp_26 <= tmp_25 + tmp_20;

  tmp_23 <= tmp_26(35 DOWNTO 12);

  rd_50_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_27 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_27 <= tmp_23;
      END IF;
    END IF;
  END PROCESS rd_50_process;


  
  tmp_28 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  p219tmp_cast <= resize(q_in_1, 25);
  p219tmp_cast_1 <= p219tmp_cast(23 DOWNTO 0);
  tmp_29 <= resize(p219tmp_cast_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 39);

  --correct false positive/nagatives
  
  tmp_30 <= '1' WHEN tmp_6 < 0 ELSE
      '0';

  p185tmp_cast <= resize(tmp_6, 25);
  p185tmp_cast_1 <=  - (p185tmp_cast);
  tmp_31 <= p185tmp_cast_1(23 DOWNTO 0);

  
  tmp_32 <= tmp_6 WHEN tmp_30 = '0' ELSE
      tmp_31;

  rd_53_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_33 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_33 <= tmp_32;
      END IF;
    END IF;
  END PROCESS rd_53_process;


  
  tmp_34 <= '1' WHEN tmp_33 < 204800 ELSE
      '0';

  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --       Generated by MATLAB 8.3, MATLAB Coder 2.6 and HDL Coder 3.4        %
  --                                                                          %
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --alpha = alpha_in/2^12;
  --1700*1700*2 dont go above this amount
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- DC Correction section
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
  tmp_35 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_40_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_36 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_36 <= tmp_35;
      END IF;
    END IF;
  END PROCESS rd_40_process;


  --dc offset threshold is higher than needed
  tmp_37 <= noise_offset + 10;

  p205_sub_cast <= resize(tmp_18, 25);
  p205_sub_cast_1 <= resize(i_dc, 25);
  p205_sub_temp <= p205_sub_cast - p205_sub_cast_1;
  p205_cast <= resize(p205_sub_temp, 34);
  p205_add_temp <= 50 + resize(noise_offset, 21);
  p205_cast_1 <= signed(resize(p205_add_temp & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p205_tmp <= tmp_38 WHEN p205_cast > p205_cast_1 ELSE
      noise_inc;
  p205_sub_cast_2 <= resize(tmp_27, 25);
  p205_sub_cast_3 <= resize(q_dc, 25);
  p205_sub_temp_1 <= p205_sub_cast_2 - p205_sub_cast_3;
  p205_cast_2 <= resize(p205_sub_temp_1, 34);
  p205_add_temp_1 <= 50 + resize(noise_offset, 21);
  p205_cast_3 <= signed(resize(p205_add_temp_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p205_tmp_1 <= p205_tmp + 1 WHEN p205_cast_2 > p205_cast_3 ELSE
      p205_tmp;
  
  tmp_39 <= to_unsigned(16#00000#, 20) WHEN tmp_36 = '1' AND (p205_tmp_1 > 10) ELSE
      p205_tmp_1 WHEN tmp_36 = '1' ELSE
      noise_inc;

  
  tmp_40 <= to_unsigned(16#00000#, 20) WHEN tmp_34 = '1' ELSE
      tmp_39;

  noise_inc_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      noise_inc <= to_unsigned(16#00000#, 20);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        noise_inc <= tmp_40;
      END IF;
    END IF;
  END PROCESS noise_inc_reg_process;


  --there is a high dc_offset value that needs to be corrected
  -- too much noise, raise cieling.
  tmp_38 <= noise_inc + 1;

  rd_51_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_42 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_42 <= tmp_41;
      END IF;
    END IF;
  END PROCESS rd_51_process;


  p217tmp_cast <= q_dc_1 & '0';
  p217tmp_cast_1 <= p217tmp_cast srl 1;
  tmp_43 <= p217tmp_cast_1(24 DOWNTO 1);

  p189_sub_cast <= resize(tmp_23, 25);
  p189_sub_cast_1 <= resize(q_dc_1, 25);
  p189_sub_temp <= p189_sub_cast - p189_sub_cast_1;
  p189_cast <= resize(p189_sub_temp, 34);
  p189_add_temp <= 50 + resize(tmp_44, 21);
  p189_cast_1 <= signed(resize(p189_add_temp & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p189_tmp <= tmp_43 WHEN p189_cast > p189_cast_1 ELSE
      q_dc_1;
  
  tmp_41 <= p189_tmp WHEN tmp_28 = '1' ELSE
      tmp_42;

  --update the q dc offset
  p220tmp_mul_temp <= to_signed(2#000111111111111#, 15) * tmp_41;
  p220tmp_cast <= p220tmp_mul_temp(37 DOWNTO 0);
  tmp_45 <= resize(p220tmp_cast, 39);

  rd_48_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_46 <= to_signed(0, 39);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_46 <= tmp_45;
      END IF;
    END IF;
  END PROCESS rd_48_process;


  tmp_47 <= tmp_46 + tmp_29;

  q_dc_1 <= tmp_47(35 DOWNTO 12);

  rd_49_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      q_dc <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        q_dc <= q_dc_1;
      END IF;
    END IF;
  END PROCESS rd_49_process;


  rd_44_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      i_dc <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        i_dc <= i_dc_1;
      END IF;
    END IF;
  END PROCESS rd_44_process;


  rd_38_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      noise_offset <= to_unsigned(16#00000#, 20);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        noise_offset <= tmp_44;
      END IF;
    END IF;
  END PROCESS rd_38_process;


  p200_sub_cast <= resize(tmp_18, 25);
  p200_sub_cast_1 <= resize(i_dc, 25);
  p200_sub_temp <= p200_sub_cast - p200_sub_cast_1;
  p200_cast <= resize(p200_sub_temp, 34);
  p200_add_temp <= 50 + resize(noise_offset, 21);
  p200_cast_1 <= signed(resize(p200_add_temp & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p200_tmp <= noise_dec WHEN p200_cast > p200_cast_1 ELSE
      tmp_48;
  p200_sub_cast_2 <= resize(tmp_27, 25);
  p200_sub_cast_3 <= resize(q_dc, 25);
  p200_sub_temp_1 <= p200_sub_cast_2 - p200_sub_cast_3;
  p200_cast_2 <= resize(p200_sub_temp_1, 34);
  p200_add_temp_1 <= 50 + resize(noise_offset, 21);
  p200_cast_3 <= signed(resize(p200_add_temp_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p200_tmp_1 <= p200_tmp WHEN p200_cast_2 > p200_cast_3 ELSE
      p200_tmp + 1;
  
  tmp_49 <= to_unsigned(16#00000#, 20) WHEN tmp_17 = '1' AND (p200_tmp_1 > 100000) ELSE
      p200_tmp_1 WHEN tmp_17 = '1' ELSE
      noise_dec;

  tmp_50 <= resize(tmp_44, 21) - 10;

  alpha_1_cast <= resize(tmp_15, 34);
  alpha_1_cast_1 <= signed(resize(tmp_50 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  alpha_relop1 <= '1' WHEN alpha_1_cast > alpha_1_cast_1 ELSE
      '0';

  
  tmp_51 <= to_unsigned(16#00000#, 20) WHEN alpha_relop1 = '1' ELSE
      tmp_49;

  noise_dec_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      noise_dec <= to_unsigned(16#00000#, 20);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        noise_dec <= tmp_51;
      END IF;
    END IF;
  END PROCESS noise_dec_reg_process;


  -- too much noise, raise cieling.
  tmp_48 <= noise_dec + 1;

  p203_sub_cast <= resize(tmp_18, 25);
  p203_sub_cast_1 <= resize(i_dc, 25);
  p203_sub_temp <= p203_sub_cast - p203_sub_cast_1;
  p203_cast <= resize(p203_sub_temp, 34);
  p203_add_temp <= 50 + resize(noise_offset, 21);
  p203_cast_1 <= signed(resize(p203_add_temp & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p203_tmp_1 <= noise_dec WHEN p203_cast > p203_cast_1 ELSE
      tmp_48;
  
  p203_tmp <= tmp_38 WHEN p203_cast > p203_cast_1 ELSE
      noise_inc;
  p203_sub_cast_2 <= resize(tmp_27, 25);
  p203_sub_cast_3 <= resize(q_dc, 25);
  p203_sub_temp_1 <= p203_sub_cast_2 - p203_sub_cast_3;
  p203_cast_2 <= resize(p203_sub_temp_1, 34);
  p203_add_temp_1 <= 50 + resize(noise_offset, 21);
  p203_cast_3 <= signed(resize(p203_add_temp_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p203_tmp_3 <= p203_tmp_1 WHEN p203_cast_2 > p203_cast_3 ELSE
      p203_tmp_1 + 1;
  
  p203_tmp_2 <= p203_tmp + 1 WHEN p203_cast_2 > p203_cast_3 ELSE
      p203_tmp;
  
  p203_tmp_4 <= tmp_37 WHEN p203_tmp_2 > 10 ELSE
      noise_offset;
  
  p203_tmp_5 <= p203_tmp_4 - 10 WHEN p203_tmp_3 > 100000 ELSE
      p203_tmp_4;
  
  tmp_44 <= p203_tmp_5 WHEN tmp_3 = '1' ELSE
      noise_offset;

  rd_45_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_53 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_53 <= tmp_52;
      END IF;
    END IF;
  END PROCESS rd_45_process;


  --update the i dc offset
  p216tmp_mul_temp <= to_signed(2#000111111111111#, 15) * tmp_52;
  p216tmp_cast <= p216tmp_mul_temp(37 DOWNTO 0);
  tmp_54 <= resize(p216tmp_cast, 39);

  rd_43_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_55 <= to_signed(0, 39);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_55 <= tmp_54;
      END IF;
    END IF;
  END PROCESS rd_43_process;


  tmp_56 <= tmp_55 + tmp_1;

  i_dc_1 <= tmp_56(35 DOWNTO 12);

  p213tmp_cast <= i_dc_1 & '0';
  p213tmp_cast_1 <= p213tmp_cast srl 1;
  tmp_57 <= p213tmp_cast_1(24 DOWNTO 1);

  p192_sub_cast <= resize(tmp_11, 25);
  p192_sub_cast_1 <= resize(i_dc_1, 25);
  p192_sub_temp <= p192_sub_cast - p192_sub_cast_1;
  p192_cast <= resize(p192_sub_temp, 34);
  p192_add_temp <= 50 + resize(tmp_44, 21);
  p192_cast_1 <= signed(resize(p192_add_temp & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  p192_tmp <= tmp_57 WHEN p192_cast > p192_cast_1 ELSE
      i_dc_1;
  
  tmp_52 <= p192_tmp WHEN tmp = '1' ELSE
      tmp_53;

  p183i_out_sub_cast <= resize(i_in_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 25);
  p183i_out_sub_cast_1 <= resize(tmp_52, 25);
  p183i_out_sub_temp <= p183i_out_sub_cast - p183i_out_sub_cast_1;
  i_out_1 <= p183i_out_sub_temp(23 DOWNTO 12);

  rd_41_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_41_reg <= (OTHERS => to_signed(2#000000000000#, 12));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_41_reg(0) <= i_out_1;
        rd_41_reg(1 TO 2) <= rd_41_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_41_process;

  i_out_tmp <= rd_41_reg(2);

  i_out <= std_logic_vector(i_out_tmp);

  p182q_out_sub_cast <= resize(q_in_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 25);
  p182q_out_sub_cast_1 <= resize(tmp_41, 25);
  p182q_out_sub_temp <= p182q_out_sub_cast - p182q_out_sub_cast_1;
  q_out_1 <= p182q_out_sub_temp(23 DOWNTO 12);

  rd_34_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_34_reg <= (OTHERS => to_signed(2#000000000000#, 12));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_34_reg(0) <= q_out_1;
        rd_34_reg(1 TO 2) <= rd_34_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_34_process;

  q_out_tmp <= rd_34_reg(2);

  q_out <= std_logic_vector(q_out_tmp);

  
  tmp_58 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  
  tmp_59 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_59_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_60 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_60 <= tmp_59;
      END IF;
    END IF;
  END PROCESS rd_59_process;


  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- 
  -- RSSI Estimation
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  tmp_61 <= i_out_1 * i_out_1;

  tmp_62 <= resize(tmp_61, 25);

  rd_42_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_63 <= to_signed(2#0000000000000000000000000#, 25);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_63 <= tmp_62;
      END IF;
    END IF;
  END PROCESS rd_42_process;


  tmp_64 <= q_out_1 * q_out_1;

  tmp_65 <= resize(tmp_64, 25);

  rd_35_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_66 <= to_signed(2#0000000000000000000000000#, 25);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_66 <= tmp_65;
      END IF;
    END IF;
  END PROCESS rd_35_process;


  tmp_67 <= tmp_63 + tmp_66;

  rssi_inst <= unsigned(tmp_67(22 DOWNTO 0));

  
  tmp_68 <= '1' WHEN rssi_inst < 5000 ELSE
      '0';

  
  tmp_69 <= '1' WHEN rssi_inst > 5000 ELSE
      '0';

  
  tmp_70 <= to_unsigned(2#000000001#, 9) WHEN tmp_69 = '1' ELSE
      counter;

  counter_1 <= tmp_71 + 1;

  
  p139_tmp <= to_unsigned(2#000000000#, 9) WHEN counter_1 >= 256 ELSE
      counter_1;
  
  tmp_72 <= to_unsigned(2#000000000#, 9) WHEN tmp_68 = '1' ELSE
      p139_tmp;

  
  tmp_73 <= '1' WHEN tmp_71 /= 0 ELSE
      '0';

  
  tmp_74 <= tmp_72 WHEN tmp_73 = '1' ELSE
      tmp_71;

  
  tmp_75 <= tmp_74 WHEN tmp_60 = '1' ELSE
      counter;

  counter_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      counter <= to_unsigned(2#000000000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        counter <= tmp_75;
      END IF;
    END IF;
  END PROCESS counter_reg_process;


  
  tmp_76 <= '1' WHEN counter = 0 ELSE
      '0';

  
  tmp_71 <= tmp_70 WHEN tmp_76 = '1' ELSE
      counter;

  
  tmp_77 <= '1' WHEN tmp_71 /= 0 ELSE
      '0';

  
  tmp_78 <= '1' WHEN rssi_inst < 5000 ELSE
      '0';

  
  tmp_79 <= '1' WHEN counter = 0 ELSE
      '0';

  
  tmp_80 <= '1' WHEN rssi_inst > 5000 ELSE
      '0';

  
  tmp_81 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_63_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_82 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_82 <= tmp_81;
      END IF;
    END IF;
  END PROCESS rd_63_process;


  
  tmp_83 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_19_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_19_reg(0) <= tmp_83;
        rd_19_reg(1) <= rd_19_reg(0);
      END IF;
    END IF;
  END PROCESS rd_19_process;

  tmp_84 <= rd_19_reg(1);

  rd_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gain_en_in_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gain_en_in_1 <= gain_en_in;
      END IF;
    END IF;
  END PROCESS rd_4_process;


  rd_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gain_en_in_2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gain_en_in_2 <= gain_en_in_1;
      END IF;
    END IF;
  END PROCESS rd_5_process;


  
  tmp_85 <= '1' WHEN gain_en_in_2 = '0' ELSE
      '0';

  rd_15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_86 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_86 <= tmp_85;
      END IF;
    END IF;
  END PROCESS rd_15_process;


  
  tmp_87 <= '1' WHEN rssi_inst > 5780000 ELSE
      '0';

  rd_68_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_88 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_88 <= tmp_87;
      END IF;
    END IF;
  END PROCESS rd_68_process;


  
  tmp_89 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_57_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_90 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_90 <= tmp_89;
      END IF;
    END IF;
  END PROCESS rd_57_process;


  tmp_91 <= resize(rssi_inst, 24);

  
  tmp_92 <= '1' WHEN tmp_71 /= 0 ELSE
      '0';

  
  tmp_93 <= '1' WHEN rssi_inst < 5000 ELSE
      '0';

  
  tmp_94 <= '1' WHEN counter = 0 ELSE
      '0';

  
  tmp_95 <= '1' WHEN rssi_inst > 5000 ELSE
      '0';

  
  tmp_96 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_58_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_97 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_97 <= tmp_96;
      END IF;
    END IF;
  END PROCESS rd_58_process;


  
  tmp_98 <= '1' WHEN tmp_71 /= 0 ELSE
      '0';

  
  tmp_99 <= '1' WHEN rssi_inst < 5000 ELSE
      '0';

  tmp_100 <= resize(rssi_inst, 33);

  
  tmp_103 <= tmp_102 WHEN tmp_99 = '1' ELSE
      tmp_101;

  
  tmp_104 <= tmp_103 WHEN tmp_98 = '1' ELSE
      tmp_102;

  
  tmp_105 <= tmp_104 WHEN tmp_97 = '1' ELSE
      rssi_sum;

  rssi_sum_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rssi_sum <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rssi_sum <= tmp_105;
      END IF;
    END IF;
  END PROCESS rssi_sum_reg_process;


  
  tmp_106 <= to_unsigned(0, 32) WHEN tmp_95 = '1' ELSE
      rssi_sum;

  
  tmp_102 <= tmp_106 WHEN tmp_94 = '1' ELSE
      rssi_sum;

  tmp_107 <= resize(tmp_102, 33);

  tmp_108 <= tmp_107 + tmp_100;

  tmp_101 <= tmp_108(31 DOWNTO 0);

  tmp_109 <= tmp_6 * tmp_6;

  tmp_110 <= resize(tmp_109, 49);

  tmp_111 <= tmp_21 * tmp_21;

  tmp_112 <= resize(tmp_111, 49);

  tmp_113 <= tmp_110 + tmp_112;

  rd_55_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_55_reg <= (OTHERS => to_signed(0, 49));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_55_reg(0) <= tmp_113;
        rd_55_reg(1) <= rd_55_reg(0);
      END IF;
    END IF;
  END PROCESS rd_55_process;

  tmp_114 <= rd_55_reg(1);

  rssi_high_goal_in_unsigned <= unsigned(rssi_high_goal_in);

  rd_9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_9_reg <= (OTHERS => to_unsigned(2#000000000000000000000000000000#, 30));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_9_reg(0) <= rssi_high_goal_in_unsigned;
        rd_9_reg(1 TO 2) <= rd_9_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_9_process;

  rssi_high_goal_in_1 <= rd_9_reg(2);

  rssi_low_goal_in_unsigned <= unsigned(rssi_low_goal_in);

  rd_10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_10_reg <= (OTHERS => to_unsigned(2#000000000000000000000000000000#, 30));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_10_reg(0) <= rssi_low_goal_in_unsigned;
        rd_10_reg(1 TO 2) <= rd_10_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_10_process;

  rssi_low_goal_in_1 <= rd_10_reg(2);

  
  tmp_115 <= '1' WHEN gain_en_in_1 = '1' ELSE
      '0';

  rd_29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_116 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_116 <= tmp_115;
      END IF;
    END IF;
  END PROCESS rd_29_process;


  
  tmp_117 <= '1' WHEN gain_en_in_2 = '0' ELSE
      '0';

  
  tmp_118 <= '1' WHEN rssi_inst > 5780000 ELSE
      '0';

  
  tmp_119 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_120 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_120 <= tmp_119;
      END IF;
    END IF;
  END PROCESS rd_21_process;


  
  tmp_121 <= '1' WHEN tmp_71 /= 0 ELSE
      '0';

  
  tmp_122 <= '1' WHEN rssi_inst < 5000 ELSE
      '0';

  rssi_en_out <= '0';

  rd_13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_13_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_13_reg(0) <= rssi_en_out;
        rd_13_reg(1) <= rd_13_reg(0);
      END IF;
    END IF;
  END PROCESS rd_13_process;

  rssi_en_out_1 <= rd_13_reg(1);

  
  p143_tmp <= '1' WHEN counter_1 >= 256 ELSE
      rssi_en_out_1;
  
  tmp_123 <= rssi_en_out_1 WHEN tmp_122 = '1' ELSE
      p143_tmp;

  rd_61_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_124 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_124 <= tmp_58;
      END IF;
    END IF;
  END PROCESS rd_61_process;


  
  tmp_125 <= tmp_123 WHEN tmp_121 = '1' ELSE
      rssi_en_out_1;

  --HDL code generation from MATLAB function: dc_offset_correction_fixpt
  -- see if the MCU has done something and if so reset
  -- latch it
  -- now!
  -- decrease by a factor of 10
  -- reset the slow gain increase
  --this overrides everything. If we're saturating, back off the gain
  --too high - decrease
  --too low - increase
  -- wait for some action and the processor is done
  -- anything in awhile.
  -- timeout is used to slowly increase the gain if we haven't recieved
  -- false alarm, reset the counter
  -- should be packet length (or smaller)
  -- yay, data
  -- if its data, accumulate it
  tmp_126 <= timeout - 1;

  
  tmp_127 <= '1' WHEN timeout > 0 ELSE
      '0';

  
  tmp_128 <= tmp_126 WHEN tmp_127 = '1' ELSE
      timeout;

  
  tmp_130 <= '1' WHEN tmp_129 > 33554432 ELSE
      '0';

  
  tmp_131 <= to_unsigned(16#0000000#, 28) WHEN tmp_130 = '1' ELSE
      tmp_129;

  
  tmp_132 <= tmp_131 WHEN tmp_120 = '1' ELSE
      timeout;

  
  tmp_133 <= to_unsigned(16#0000000#, 28) WHEN tmp_118 = '1' ELSE
      tmp_132;

  
  tmp_134 <= tmp_133 WHEN tmp_117 = '1' ELSE
      tmp_132;

  
  tmp_136 <= '0' WHEN tmp_116 = '1' ELSE
      tmp_135;

  rd_28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_137 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_137 <= tmp_136;
      END IF;
    END IF;
  END PROCESS rd_28_process;


  rd_67_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_138 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_138 <= tmp_135;
      END IF;
    END IF;
  END PROCESS rd_67_process;


  
  alpha_relop1_1 <= '1' WHEN resize(rssi_diff, 30) < rssi_low_goal_in_1 ELSE
      '0';

  
  tmp_139 <= '1' WHEN alpha_relop1_1 = '1' ELSE
      tmp_138;

  p88tmp_cast <= resize(c, 51);
  p88tmp_cast_1 <=  - (p88tmp_cast);
  tmp_140 <= p88tmp_cast_1(49 DOWNTO 0);

  p145_cast <= tmp_101 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  p145_cast_1 <= p145_cast srl 8;
  p145_add_cast <= resize(p145_cast_1(39 DOWNTO 7), 34);
  p145_add_temp <= p145_add_cast + to_unsigned(1, 34);
  p145_cast_2 <= p145_add_temp(33 DOWNTO 1);
  
  p145_tmp <= p145_cast_2(23 DOWNTO 0) WHEN counter_1 >= 256 ELSE
      tmp_141;
  
  tmp_142 <= tmp_141 WHEN tmp_93 = '1' ELSE
      p145_tmp;

  
  tmp_143 <= tmp_142 WHEN tmp_92 = '1' ELSE
      tmp_141;

  
  tmp_144 <= '1' WHEN tmp_129 > 33554432 ELSE
      '0';

  
  tmp_145 <= tmp_91 WHEN tmp_144 = '1' ELSE
      tmp_143;

  
  tmp_146 <= tmp_145 WHEN tmp_90 = '1' ELSE
      tmp_141;

  rd_56_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_141 <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_141 <= tmp_146;
      END IF;
    END IF;
  END PROCESS rd_56_process;


  -- dir_out = 0 - do nothing
  -- dir_out = 1 - increase
  -- dir_out = 2 - decrease
  -- dir_out = 3 - decrease a lot (were saturating)
  -- only increase power if the rssi is away from the mean
  p89c_sub_cast <= signed(resize(tmp_141 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50));
  p89c_sub_cast_1 <= resize(tmp_114, 50);
  c <= p89c_sub_cast - p89c_sub_cast_1;

  
  tmp_147 <= '1' WHEN c < to_signed(0, 50) ELSE
      '0';

  
  tmp_148 <= c WHEN tmp_147 = '0' ELSE
      tmp_140;

  rssi_diff <= unsigned(tmp_148(47 DOWNTO 24));

  
  alpha_relop1_2 <= '1' WHEN resize(rssi_diff, 30) > rssi_high_goal_in_1 ELSE
      '0';

  
  tmp_149 <= '1' WHEN alpha_relop1_2 = '1' ELSE
      tmp_139;

  
  tmp_151 <= '1' WHEN tmp_150 = '1' ELSE
      '0';

  
  tmp_152 <= tmp_149 WHEN tmp_151 = '1' ELSE
      tmp_138;

  
  tmp_153 <= '1' WHEN tmp_88 = '1' ELSE
      tmp_152;

  
  tmp_154 <= tmp_153 WHEN tmp_86 = '1' ELSE
      tmp_138;

  tmp_155 <= tmp_135;

  rd_66_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_156 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_156 <= tmp_155;
      END IF;
    END IF;
  END PROCESS rd_66_process;


  p48_output : PROCESS (tmp_156, tmp_154, tmp_137)
    VARIABLE tmp157 : std_logic;
  BEGIN

    CASE tmp_156 IS
      WHEN '0' =>
        tmp157 := tmp_154;
      WHEN '1' =>
        tmp157 := tmp_137;
      WHEN OTHERS => 
        tmp157 := '0';
    END CASE;

    tmp_158 <= tmp157;
  END PROCESS p48_output;


  
  tmp_159 <= tmp_158 WHEN tmp_84 = '1' ELSE
      tmp_138;

  tmp_135 <= tmp_159;

  tmp_160 <= tmp_135;

  p54_output : PROCESS (tmp_160, tmp_134, tmp_132)
    VARIABLE tmp161 : unsigned(27 DOWNTO 0);
  BEGIN

    CASE tmp_160 IS
      WHEN '0' =>
        tmp161 := tmp_134;
      WHEN '1' =>
        tmp161 := tmp_132;
      WHEN OTHERS => 
        tmp161 := tmp_132;
    END CASE;

    tmp_162 <= tmp161;
  END PROCESS p54_output;


  
  tmp_163 <= tmp_162 WHEN tmp_82 = '1' ELSE
      tmp_132;

  timeout_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      timeout <= to_unsigned(16#0000000#, 28);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        timeout <= tmp_163;
      END IF;
    END IF;
  END PROCESS timeout_reg_process;


  -- we think we have data
  tmp_164 <= timeout + 1;

  
  tmp_165 <= tmp_164 WHEN tmp_80 = '0' ELSE
      tmp_128;

  
  tmp_166 <= tmp_165 WHEN tmp_79 = '1' ELSE
      timeout;

  
  p141_tmp <= to_unsigned(16#0000000#, 28) WHEN counter_1 >= 256 ELSE
      tmp_166;
  
  tmp_167 <= tmp_166 WHEN tmp_78 = '1' ELSE
      p141_tmp;

  
  tmp_129 <= tmp_167 WHEN tmp_77 = '1' ELSE
      tmp_166;

  
  tmp_168 <= '1' WHEN tmp_129 > 33554432 ELSE
      '0';

  
  tmp_169 <= '1' WHEN tmp_168 = '1' ELSE
      tmp_125;

  
  tmp_170 <= tmp_169 WHEN tmp_124 = '1' ELSE
      rssi_en_out_1;

  rd_62_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_150 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_150 <= tmp_170;
      END IF;
    END IF;
  END PROCESS rd_62_process;


  
  tmp_171 <= '1' WHEN tmp_150 = '1' ELSE
      '0';

  
  tmp_172 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_173 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_173 <= tmp_172;
      END IF;
    END IF;
  END PROCESS rd_24_process;


  
  tmp_174 <= '1' WHEN tmp_71 /= 0 ELSE
      '0';

  
  tmp_175 <= '1' WHEN rssi_inst < 5000 ELSE
      '0';

  rssi_out_1 <= to_unsigned(16#000000#, 24);

  rd_0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_0_reg <= (OTHERS => to_unsigned(16#000000#, 24));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_0_reg(0) <= rssi_out_1;
        rd_0_reg(1) <= rd_0_reg(0);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  rssi_out_2 <= rd_0_reg(1);

  p147_cast <= tmp_101 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  p147_cast_1 <= p147_cast srl 8;
  p147_add_cast <= resize(p147_cast_1(39 DOWNTO 7), 34);
  p147_add_temp <= p147_add_cast + to_unsigned(1, 34);
  p147_cast_2 <= p147_add_temp(33 DOWNTO 1);
  
  p147_tmp <= p147_cast_2(23 DOWNTO 0) WHEN counter_1 >= 256 ELSE
      rssi_out_2;
  
  tmp_176 <= rssi_out_2 WHEN tmp_175 = '1' ELSE
      p147_tmp;

  
  tmp_177 <= tmp_176 WHEN tmp_174 = '1' ELSE
      rssi_out_2;

  
  tmp_178 <= tmp_177 WHEN tmp_173 = '1' ELSE
      rssi_out_2;

  rd_60_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_179 <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_179 <= tmp_178;
      END IF;
    END IF;
  END PROCESS rd_60_process;


  rssi_latch_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rssi_latch <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rssi_latch <= tmp_180;
      END IF;
    END IF;
  END PROCESS rssi_latch_reg_process;


  
  tmp_180 <= tmp_179 WHEN tmp_171 = '1' ELSE
      rssi_latch;

  rd_22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rssi_out_tmp <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rssi_out_tmp <= tmp_180;
      END IF;
    END IF;
  END PROCESS rd_22_process;


  rssi_out <= std_logic_vector(rssi_out_tmp);

  
  tmp_181 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_20_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_20_reg(0) <= tmp_181;
        rd_20_reg(1) <= rd_20_reg(0);
      END IF;
    END IF;
  END PROCESS rd_20_process;

  tmp_182 <= rd_20_reg(1);

  tmp_183 <= tmp_135;

  rd_65_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_184 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_184 <= tmp_183;
      END IF;
    END IF;
  END PROCESS rd_65_process;


  
  tmp_185 <= '1' WHEN gain_en_in_2 = '0' ELSE
      '0';

  
  tmp_186 <= '1' WHEN rssi_inst > 5780000 ELSE
      '0';

  rd_26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_187 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_187 <= tmp_186;
      END IF;
    END IF;
  END PROCESS rd_26_process;


  
  alpha_relop1_3 <= '1' WHEN resize(rssi_diff, 30) > rssi_high_goal_in_1 ELSE
      '0';

  
  alpha_relop1_4 <= '1' WHEN resize(rssi_diff, 30) < rssi_low_goal_in_1 ELSE
      '0';

  dir_en_out <= '0';

  rd_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dir_en_out_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dir_en_out_1 <= dir_en_out;
      END IF;
    END IF;
  END PROCESS rd_2_process;


  rd_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_3_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_3_reg(0) <= dir_en_out_1;
        rd_3_reg(1) <= rd_3_reg(0);
      END IF;
    END IF;
  END PROCESS rd_3_process;

  dir_en_out_2 <= rd_3_reg(1);

  
  tmp_188 <= '1' WHEN tmp_150 = '1' ELSE
      '0';

  
  tmp_189 <= '1' WHEN alpha_relop1_4 = '1' ELSE
      dir_en_out_2;

  
  tmp_190 <= '1' WHEN alpha_relop1_3 = '1' ELSE
      tmp_189;

  rd_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_191 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_191 <= tmp_185;
      END IF;
    END IF;
  END PROCESS rd_1_process;


  
  tmp_192 <= tmp_190 WHEN tmp_188 = '1' ELSE
      dir_en_out_2;

  
  tmp_193 <= '1' WHEN tmp_187 = '1' ELSE
      tmp_192;

  
  tmp_194 <= tmp_193 WHEN tmp_191 = '1' ELSE
      dir_en_out_2;

  
  tmp_195 <= '1' WHEN gain_en_in_1 = '1' ELSE
      '0';

  
  tmp_196 <= '1' WHEN tmp_195 = '1' ELSE
      dir_en_out_1;

  rd_30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_30_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_30_reg(0) <= tmp_196;
        rd_30_reg(1) <= rd_30_reg(0);
      END IF;
    END IF;
  END PROCESS rd_30_process;

  tmp_197 <= rd_30_reg(1);

  p50_output : PROCESS (tmp_184, tmp_194, tmp_197, dir_en_out_2)
    VARIABLE tmp198 : std_logic;
  BEGIN

    CASE tmp_184 IS
      WHEN '0' =>
        tmp198 := tmp_194;
      WHEN '1' =>
        tmp198 := tmp_197;
      WHEN OTHERS => 
        tmp198 := dir_en_out_2;
    END CASE;

    tmp_199 <= tmp198;
  END PROCESS p50_output;


  
  tmp_200 <= tmp_199 WHEN tmp_182 = '1' ELSE
      dir_en_out_2;

  
  tmp_201 <= '1' WHEN tmp_200 = '1' ELSE
      '0';

  
  tmp_202 <= '1' WHEN rx_en_in_1 = '1' ELSE
      '0';

  rd_64_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_64_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_64_reg(0) <= tmp_202;
        rd_64_reg(1) <= rd_64_reg(0);
      END IF;
    END IF;
  END PROCESS rd_64_process;

  tmp_203 <= rd_64_reg(1);

  tmp_204 <= tmp_135;

  rd_27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_205 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_205 <= tmp_204;
      END IF;
    END IF;
  END PROCESS rd_27_process;


  
  tmp_206 <= '1' WHEN gain_en_in_2 = '0' ELSE
      '0';

  
  tmp_207 <= '1' WHEN rssi_inst > 5780000 ELSE
      '0';

  rd_32_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_208 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_208 <= tmp_207;
      END IF;
    END IF;
  END PROCESS rd_32_process;


  
  alpha_relop1_5 <= '1' WHEN resize(rssi_diff, 30) > rssi_high_goal_in_1 ELSE
      '0';

  
  alpha_relop1_6 <= '1' WHEN resize(rssi_diff, 30) < rssi_low_goal_in_1 ELSE
      '0';

  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- Gain Correction
  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  dir_out_1 <= to_unsigned(2#00#, 2);

  rd_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dir_out_2 <= to_unsigned(2#00#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dir_out_2 <= dir_out_1;
      END IF;
    END IF;
  END PROCESS rd_6_process;


  rd_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_7_reg <= (OTHERS => to_unsigned(2#00#, 2));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_7_reg(0) <= dir_out_2;
        rd_7_reg(1) <= rd_7_reg(0);
      END IF;
    END IF;
  END PROCESS rd_7_process;

  dir_out_3 <= rd_7_reg(1);

  
  tmp_209 <= '1' WHEN tmp_150 = '1' ELSE
      '0';

  
  tmp_210 <= to_unsigned(2#01#, 2) WHEN alpha_relop1_6 = '1' ELSE
      dir_out_3;

  
  tmp_211 <= to_unsigned(2#10#, 2) WHEN alpha_relop1_5 = '1' ELSE
      tmp_210;

  rd_8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_212 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_212 <= tmp_206;
      END IF;
    END IF;
  END PROCESS rd_8_process;


  
  tmp_213 <= tmp_211 WHEN tmp_209 = '1' ELSE
      dir_out_3;

  
  tmp_214 <= to_unsigned(2#11#, 2) WHEN tmp_208 = '1' ELSE
      tmp_213;

  
  tmp_215 <= tmp_214 WHEN tmp_212 = '1' ELSE
      dir_out_3;

  
  tmp_216 <= '1' WHEN gain_en_in_1 = '1' ELSE
      '0';

  
  tmp_217 <= to_unsigned(2#00#, 2) WHEN tmp_216 = '1' ELSE
      dir_out_2;

  rd_31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_31_reg <= (OTHERS => to_unsigned(2#00#, 2));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_31_reg(0) <= tmp_217;
        rd_31_reg(1) <= rd_31_reg(0);
      END IF;
    END IF;
  END PROCESS rd_31_process;

  tmp_218 <= rd_31_reg(1);

  p52_output : PROCESS (tmp_205, tmp_215, tmp_218, dir_out_3)
    VARIABLE tmp219 : unsigned(1 DOWNTO 0);
  BEGIN

    CASE tmp_205 IS
      WHEN '0' =>
        tmp219 := tmp_215;
      WHEN '1' =>
        tmp219 := tmp_218;
      WHEN OTHERS => 
        tmp219 := dir_out_3;
    END CASE;

    tmp_220 <= tmp219;
  END PROCESS p52_output;


  
  tmp_221 <= tmp_220 WHEN tmp_203 = '1' ELSE
      dir_out_3;

  dir_latch_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dir_latch <= to_unsigned(2#00#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dir_latch <= tmp_222;
      END IF;
    END IF;
  END PROCESS dir_latch_reg_process;


  
  tmp_222 <= tmp_221 WHEN tmp_201 = '1' ELSE
      dir_latch;

  rd_16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dir_out_tmp <= to_unsigned(2#00#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dir_out_tmp <= tmp_222;
      END IF;
    END IF;
  END PROCESS rd_16_process;


  dir_out <= std_logic_vector(dir_out_tmp);

  blinky_cnt_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      blinky_cnt <= to_unsigned(2#00000000000000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        blinky_cnt <= tmp_223;
      END IF;
    END IF;
  END PROCESS blinky_cnt_reg_process;


  --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  tmp_224 <= blinky_cnt;

  tmp_225 <= resize(tmp_224, 15);

  tmp_226 <= tmp_225 + 1;

  tmp_223 <= tmp_226(13 DOWNTO 0);

  tmp_227 <= tmp_223 * 13743;

  blinky_1 <= '0';

  blinky_2 <= blinky_1;

  out_4_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      blinky_3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        blinky_3 <= blinky_2;
      END IF;
    END IF;
  END PROCESS out_4_pipe_process;


  out_4_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      blinky_4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        blinky_4 <= blinky_3;
      END IF;
    END IF;
  END PROCESS out_4_pipe_1_process;


  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= blinky_4;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  blinky <= delayMatch_reg(1);

  rd_25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d1_tmp <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d1_tmp <= rssi_diff;
      END IF;
    END IF;
  END PROCESS rd_25_process;


  d1 <= std_logic_vector(d1_tmp);

  d2_1 <= resize(rssi_inst, 24);

  out_6_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d2_2 <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d2_2 <= d2_1;
      END IF;
    END IF;
  END PROCESS out_6_pipe_process;


  out_6_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d2_tmp <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d2_tmp <= d2_2;
      END IF;
    END IF;
  END PROCESS out_6_pipe_1_process;


  d2 <= std_logic_vector(d2_tmp);

  out_7_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d3_1 <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d3_1 <= tmp_146;
      END IF;
    END IF;
  END PROCESS out_7_pipe_process;


  out_7_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d3_tmp <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d3_tmp <= d3_1;
      END IF;
    END IF;
  END PROCESS out_7_pipe_1_process;


  d3 <= std_logic_vector(d3_tmp);

  rd_23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d4_tmp <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d4_tmp <= tmp_180;
      END IF;
    END IF;
  END PROCESS rd_23_process;


  d4 <= std_logic_vector(d4_tmp);

  rd_17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d5_tmp <= to_unsigned(2#00#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d5_tmp <= tmp_222;
      END IF;
    END IF;
  END PROCESS rd_17_process;


  d5 <= std_logic_vector(d5_tmp);

  d6_1 <= resize(tmp_163, 30);

  out_10_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d6_2 <= to_unsigned(2#000000000000000000000000000000#, 30);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d6_2 <= d6_1;
      END IF;
    END IF;
  END PROCESS out_10_pipe_process;


  out_10_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d6_tmp <= to_unsigned(2#000000000000000000000000000000#, 30);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d6_tmp <= d6_2;
      END IF;
    END IF;
  END PROCESS out_10_pipe_1_process;


  d6 <= std_logic_vector(d6_tmp);

  d7_1 <= tmp_170;

  d7_2 <= d7_1;

  out_11_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d7_3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d7_3 <= d7_2;
      END IF;
    END IF;
  END PROCESS out_11_pipe_process;


  out_11_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      d7 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        d7 <= d7_3;
      END IF;
    END IF;
  END PROCESS out_11_pipe_1_process;


  d8_1 <= rx_en_in_1;

  d8_2 <= d8_1;

  rd_18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rd_18_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rd_18_reg(0) <= d8_2;
        rd_18_reg(1 TO 2) <= rd_18_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_18_process;

  d8 <= rd_18_reg(2);

  gain_in_unsigned <= unsigned(gain_in);

  in_6_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gain_in_1 <= to_unsigned(2#000000#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gain_in_1 <= gain_in_unsigned;
      END IF;
    END IF;
  END PROCESS in_6_pipe_process;


  in_6_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gain_in_2 <= to_unsigned(2#000000#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gain_in_2 <= gain_in_1;
      END IF;
    END IF;
  END PROCESS in_6_pipe_1_process;


  out_13_pipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gain_out_1 <= to_unsigned(2#000000#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gain_out_1 <= gain_in_2;
      END IF;
    END IF;
  END PROCESS out_13_pipe_process;


  out_13_pipe_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gain_out_tmp <= to_unsigned(2#000000#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gain_out_tmp <= gain_out_1;
      END IF;
    END IF;
  END PROCESS out_13_pipe_1_process;


  gain_out <= std_logic_vector(gain_out_tmp);

  ce_out <= clk_enable;

END rtl;

